repos:
  - repo: local
    hooks:
      - id: isort-check
        name: isort-check 
        entry: isort src/.
        language: system
        types: [python]
        args: ["--profile", "black"]
        stages: [commit]
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--rcfile=.pylintrc", # Link to your config file
            "--load-plugins=pylint.extensions.docparams", # Load an extension
          ]
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c '.venv/bin/pip3 freeze > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: bash -c 'pytest -sv'
        language: system
        pass_filenames: false
        stages: [commit]
